# Generated by Django 3.0.8 on 2020-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200807_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favourite_cuisine',
            field=models.CharField(choices=[('French', 'French'), ('Italian', 'Italian'), ('Modern Australian', 'Modern Australian')], default='Modern Australian', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
