# Generated by Django 3.0.8 on 2020-08-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsstory_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_upload',
            field=models.URLField(default='https://en.wikipedia.org/wiki/Standard_Schnauzer#/media/File:Emppumenossa.jpg'),
        ),
    ]
