# Generated by Django 3.0.8 on 2020-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200802_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_upload',
            field=models.URLField(default='', max_length=500),
        ),
    ]
