# Generated by Django 3.0.8 on 2020-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200805_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='cuisine_type',
            field=models.CharField(choices=[('French', 'French'), ('Italian', 'Italian'), ('Modern Australian', 'Modern Australian')], default='Modern Australian', max_length=20),
        ),
    ]
