# Generated by Django 3.0.8 on 2020-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsstory_cuisine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='Food_rating',
            field=models.CharField(choices=[('French', 'French'), ('Italian', 'Italian'), ('Modern Australian', 'Modern Australian')], default=3, max_length=20),
        ),
    ]
