# Generated by Django 3.0.8 on 2020-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsstory_food_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='Food_rating',
            field=models.CharField(choices=[('French', 'French'), ('Italian', 'Italian'), ('Modern Australian', 'Modern Australian'), ('Indonesian', 'Indonesian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Thai', 'Thai'), ('American', 'American'), ('Middle Eastern', 'Middle Eastern'), ('Indian', 'Indian'), ('Moroccan', 'Moroccan'), ('Other', 'Other')], default=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='cuisine_type',
            field=models.CharField(choices=[('French', 'French'), ('Italian', 'Italian'), ('Modern Australian', 'Modern Australian'), ('Indonesian', 'Indonesian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Thai', 'Thai'), ('American', 'American'), ('Middle Eastern', 'Middle Eastern'), ('Indian', 'Indian'), ('Moroccan', 'Moroccan'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
