# Generated by Django 3.0.8 on 2020-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200811_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='Restaurant',
            field=models.CharField(default='Restaurant-name', max_length=200),
        ),
    ]
