# Generated by Django 3.0.8 on 2020-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_newsstory_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='Restaurant',
            field=models.CharField(max_length=200),
        ),
    ]
