# Generated by Django 3.0.8 on 2020-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200812_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='Food_rating',
            field=models.CharField(choices=[('1', 'Awful'), ('2', 'Average'), ('3', 'Okay'), ('4', 'Good'), ('5', 'Fantastic')], default=3, max_length=20),
        ),
    ]
