# Generated by Django 3.0.8 on 2020-08-13 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0016_auto_20200813_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
